# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- env
- locale
- rvm use 2.2.2 --install --binary --fuzzy 
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- ruby -rsimctl -e 'SimCtl.warmup("iPhone 5", "iOS 9.3", 60)'
script:
- set -o pipefail && xcodebuild test -workspace Example/acceptSDK.xcworkspace -scheme AcceptDemo -destination 'platform=iOS Simulator,name=iPhone 5,OS=9.3' ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
